apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: techcrux-sa
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "techcrux-secrets"
      imagePullSecrets:     
        - name: my-registry-key
      containers:
        - name: website
          image: vickcode/my-website:1.6
          ports:
            - containerPort: 3000
          env:
            - name: EMAIL_USER
              value: "victordickson474@gmail.com"
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: myk8ssecrets
                  key: email-password
          volumeMounts:
          - name: secrets-store-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: website-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  selector:
    app: website
  ports:
    - port: 3000
      targetPort: 3000
