apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      imagePullSecrets:     
        - name: my-registry-key
      containers:
      - name: website
        image: vickcode/my-website:1.5
        ports:
        - containerPort: 3000
		env:
          - name: EMAIL_USER
            value: "victordickson474@gmail.com"
          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name: email-secret
                key: password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: website-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: website
spec:
  type: NodePort
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 3000
